FROM httpd:2.4
COPY ./asset/ /usr/local/apache2/htdocs/asset/
COPY ./index.html /usr/local/apache2/htdocs/
COPY ./gitcommit.html /usr/local/apache2/htdocs/
COPY ./docker.html /usr/local/apache2/htdocs/
COPY ./distributed.html /usr/local/apache2/htdocs/
